/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 TRF-compressed.glb 
*/

import React from 'react'
import { BakeShadows, useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/TRF-compressed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes['7386735-1'].geometry} material={materials.PaletteMaterial001} position={[-1.153, 0.248, 4.595]} />
      <BakeShadows />
      <mesh
        castShadow
        geometry={nodes['7386999-1'].geometry}
        material={materials.PaletteMaterial001}
        position={[-1.103, 0.167, 1.595]}
        rotation={[0, -Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/TRF-compressed.glb')
